# Generated by Django 5.0.4 on 2024-05-16 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_comment_options_alter_comment_estimation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='estimation',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Оценка'),
        ),
    ]
