# Generated by Django 5.0.4 on 2024-05-19 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_customuser_access_write_comments_complaints'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='showing',
            field=models.BooleanField(default=True, verbose_name='Отображать'),
        ),
    ]
