# Generated by Django 4.2.6 on 2023-10-31 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.ImageField(upload_to='products/img/', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='productphoto',
            name='product_photo',
            field=models.ImageField(upload_to='products/img/'),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='image',
            field=models.ImageField(upload_to='products/img/', verbose_name='Изображение'),
        ),
    ]
