# Generated by Django 5.0.4 on 2024-12-29 20:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_alter_customuser_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='access_write_comments',
            new_name='can_write_comments',
        ),
    ]
