# Generated by Django 5.0.4 on 2024-04-20 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basket', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='basket',
            old_name='created_add',
            new_name='created_at',
        ),
    ]
