# Generated by Django 5.0.4 on 2024-04-28 19:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basket', '0003_rename_created_add_basket_created_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='basket',
            options={'ordering': ['-id'], 'verbose_name': 'Корзина', 'verbose_name_plural': 'Корзины'},
        ),
    ]
